### ISSUE TITLE
logSource.ClearLogs is not clearing the log

### ISSUE THREAD

**Issue by pklaes** [AndrewKeepCoding/serilog-sinks-memorysink#2]
When I read all log entries with `logSource.GetLogs` and try to clear the log with logSource.ClearLogs , the log remains unchanged. Another call to `logSource.GetLogs` returns the very same entries as before. I would expect `logSource.GetLogs` to return no entries afterwards.

Inspecting the code, I found in `MemorySink.cs` :

```
 public async Task ClearLogs(CancellationToken cancellationToken = default)
    {
        if (LogCollection.Count > 0)
        {
            return;
        }
 [...]
```
I guess this should read  `if (LogCollection.Count <= 0)` ?

**Comment by AndrewKeepCoding** [comment]
You are 100% right! I'll fix this soon. Thanks!
